### PR TITLE
Clarify barrier in shmem_malloc_hints is on SHMEM_TEAM_WORLD

### PR DESCRIPTION
**Pull request by agrippa**

### CODE REVIEW

**Comment by agrippa** [comment]
@manjugv @minsii @swpoole @jamesaross @tonycurtis please take a look

**Comment by agrippa** [comment]
Addressing https://github.com/openshmem-org/specification/issues/352

**Review by tonycurtis — APPROVED** [review]

**Comment by minsii** [comment]
approve

**Comment by jdinan** [comment]
Could you please cross check with the `shmem_malloc` text? I believe it's phrased differently there, and may provide a clearer specification for what contexts (if any) are quieted by the operation. The quiet on the default context was included for backward compatibility with the legacy, non-context APIs. Given that this is a new memory allocation routine, should we consider whether we want a barrier or sync (no quiet) semantic?

**Comment by agrippa** [comment]
@jdinan the text here seems to match the phrasing in shmem_malloc pretty closely (i.e. looks like it has been copy pasted for the most part).

I'm personally in favor of keeping this a barrier for now to keep it consistent with all of the other memory routines, as we aren't changing those to be a sync in 1.5. Longer term (i.e. 1.6) I think discussion is needed around whether we really want to change these to sync. I see the arguments for moving to sync being:

1. It doesn't make much sense to rely on memory management routines to quiesce operations.
2. Reducing the cost of shmem_malloc and similar routines by not forcing a quiet could help improve start up times for apps.

On the other hand, these routines are generally going to be called infrequently in any real apps, and likely just once at start up so the performance benefit may be negligible for any programs that don't have a trivial execution time.

**Comment by jdinan** [comment]
The barriers are only there to support existing programs that use the legacy API (assuming you view the non-context point-to-point operations as legacy and not as a convenience feature that should be carried forward). This new memory management routine doesn't have any legacy API concerns, so we can define it without the overhead of the quiet. Once there are user programs written to the new memory allocation API, such a change becomes harder.

I tend to agree with your assessment above; I don't see the memory management APIs as significant sources of overhead for most applications.

**Comment by jdinan** [comment]
@agrippa I thought we had some text written by @davidozog that stated malloc/free perform an operation that is "semantically equivalent" to a barrier. Maybe this was changed as part of the teams proposal?

**Comment by agrippa** [comment]
@jdinan I get that the barrier is only there because that's how it was in the legacy APIs (for whatever reason), but I also think it would be confusing to have every single memory management routine have some kind of implicit barrier, except one. So if it's a tradeoff between what we think is a negligible performance hit and a potentially confusing semantic, i'd prefer the negligible performance hit. I also don't think removing the barrier is something we can cover in a doc edit, as that would be a semantic change the committee should agree to. I'd imagine that if we want to change the barrier semantics of the other APIs to be sync, we'd include shmem_malloc_hints in that change.

**Comment by agrippa** [comment]
And on your second comment, we do but we also don't.

For example, we have the wording "Otherwise, each of these routines includes at least one call to a procedure that is semantically equivalent to shmem_barrier_all" for the other management routines but then we also say "shmem_malloc and shmem_align call a barrier on exit". In shmem_malloc_hints we say something consistent with that part of the paragraph, i.e. "the routine will call a barrier on exit".

It sounds like you're suggesting we merge that wording, something like "Otherwise, the routine will call a procedure that is semantically equivalent to shmem_barrier_all on exit"? How does that sound?

**Comment by jdinan** [comment]
@agrippa Appreciate the critical discussion, and support your conclusions above.

**Comment by manjugv** [comment]
Sorry for pitching in late (did not see this conversation). My preference is also to keep it consistent with other memory allocation routines. 

I agree with the changes.

**Review by manjugv — APPROVED** [review]

**Review by minsii — APPROVED** [review]

**Review by tonycurtis — APPROVED** [review]

**Comment by swpoole** [comment]
Looks good and approved.

**Comment by manjugv** [comment]
@agrippa Can I merge this ?

**Comment by agrippa** [comment]
@manjugv yep, this is ready to go.

**Comment by jamesaross** [comment]
👍

**Pull request merged**
