### PR TITLE
section/memory: replace default team with world team

### PR DESCRIPTION
**Pull request by minsii**
Resolves #371 for the memory management section.

### CODE REVIEW

**Comment by minsii** [comment]
We have discussed in the collectives section committee that "world team" should be better than "default team" as it is a more straightforward term. This is a whole-doc change. This PR addresses it for the memory management section.
@agrippa @manjugv  @swpoole @jamesaross @tonycurtis Can you please review?

**Review by agrippa — APPROVED** [review]

**Review by manjugv — APPROVED** [review]

**Comment by manjugv** [comment]
@minsii Is this ready to go ?

**Comment by minsii** [comment]
@manjugv Yes

**Comment by manjugv** [comment]
@swpoole @jamesaross @tonycurtis can you please review and approve ?

**Review by tonycurtis — APPROVED** [review]

**Comment by swpoole** [comment]
Approved.

**Comment by manjugv** [comment]
Thanks committee

**Pull request merged**
